"""Shared enumerations for the canonical domain model."""

from enum import StrEnum


class BundleType(StrEnum):
    """The four document intake patterns described in the platform spec."""

    A_CMS1500_SINGLE = "A_CMS1500_SINGLE"
    B_CMS1500_BUNDLE = "B_CMS1500_BUNDLE"
    C_UB_SINGLE = "C_UB_SINGLE"
    D_UNSTRUCTURED = "D_UNSTRUCTURED"
    UNKNOWN_STRUCTURED = "UNKNOWN_STRUCTURED"
    UNKNOWN_UNSTRUCTURED = "UNKNOWN_UNSTRUCTURED"
    NON_CLAIM = "NON_CLAIM"


class SourceFormat(StrEnum):
    TIFF = "TIFF"
    PDF = "PDF"
    PNG = "PNG"
    JPEG = "JPEG"
    UNKNOWN = "UNKNOWN"


class CompressionType(StrEnum):
    UNCOMPRESSED = "UNCOMPRESSED"
    CCITT_G3 = "CCITT_G3"
    CCITT_G4 = "CCITT_G4"
    LZW = "LZW"
    JPEG = "JPEG"
    DEFLATE = "DEFLATE"
    PACKBITS = "PACKBITS"
    OTHER = "OTHER"


class DocumentStatus(StrEnum):
    RECEIVED = "RECEIVED"
    DUPLICATE = "DUPLICATE"
    PREPARING = "PREPARING"
    PREPARED = "PREPARED"
    CLASSIFYING = "CLASSIFYING"
    ROUTED = "ROUTED"
    EXTRACTING = "EXTRACTING"
    VALIDATING = "VALIDATING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COMPLETED = "COMPLETED"
    OUTPUT_GENERATED = "OUTPUT_GENERATED"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"


class PageRole(StrEnum):
    """What a page was determined to be, once classified."""

    CMS1500_CLAIM_PAGE = "CMS1500_CLAIM_PAGE"
    UB_CLAIM_PAGE = "UB_CLAIM_PAGE"
    UNSTRUCTURED_CLAIM_PAGE = "UNSTRUCTURED_CLAIM_PAGE"
    ATTACHMENT = "ATTACHMENT"
    UNKNOWN = "UNKNOWN"


class ClassificationMethod(StrEnum):
    TRUSTED_ANCHOR_SKIP = "TRUSTED_ANCHOR_SKIP"
    ANCHOR_PHRASE = "ANCHOR_PHRASE"
    GRID_LAYOUT_SIGNATURE = "GRID_LAYOUT_SIGNATURE"
    TEMPLATE_SIMILARITY = "TEMPLATE_SIMILARITY"
    MOBILENET_FALLBACK = "MOBILENET_FALLBACK"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ExtractionMethod(StrEnum):
    CACHE_HIT = "CACHE_HIT"
    TEMPLATE_RULES = "TEMPLATE_RULES"
    OPENCV_ALIGNMENT = "OPENCV_ALIGNMENT"
    REGIONAL_PADDLEOCR = "REGIONAL_PADDLEOCR"
    REGIONAL_RAPIDOCR = "REGIONAL_RAPIDOCR"
    PPOCR_V5_CHALLENGER = "PPOCR_V5_CHALLENGER"
    ALTERNATE_PREPROCESS_OCR = "ALTERNATE_PREPROCESS_OCR"
    LAYOUTLMV3 = "LAYOUTLMV3"
    TABLE_TRANSFORMER = "TABLE_TRANSFORMER"
    TROCR = "TROCR"
    VLM_FALLBACK = "VLM_FALLBACK"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class FieldCriticality(StrEnum):
    CRITICAL = "CRITICAL"
    NON_CRITICAL = "NON_CRITICAL"


class FieldDisposition(StrEnum):
    VALIDATED_AUTOMATICALLY = "VALIDATED_AUTOMATICALLY"
    VERIFIED_BY_HUMAN = "VERIFIED_BY_HUMAN"
    NEEDS_RETRY = "NEEDS_RETRY"


class ValidationStatus(StrEnum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    OVERRIDDEN = "OVERRIDDEN"


class ReviewTaskStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ReviewReasonCode(StrEnum):
    OCR_DISAGREEMENT = "OCR_DISAGREEMENT"
    LOW_OCR_CONFIDENCE = "LOW_OCR_CONFIDENCE"
    LOW_REGISTRATION_CONFIDENCE = "LOW_REGISTRATION_CONFIDENCE"
    NO_REFERENCE_MATCH = "NO_REFERENCE_MATCH"
    REFERENCE_CONTRADICTION = "REFERENCE_CONTRADICTION"
    CRITICAL_NAME_UNVERIFIED = "CRITICAL_NAME_UNVERIFIED"
    INVALID_FORMAT = "INVALID_FORMAT"
    EMPTY_CROP = "EMPTY_CROP"
    WRONG_CROP_SUSPECTED = "WRONG_CROP_SUSPECTED"
    LABEL_CONTAMINATION = "LABEL_CONTAMINATION"
    CHECKBOX_AMBIGUOUS = "CHECKBOX_AMBIGUOUS"
    ADDRESS_AMBIGUOUS = "ADDRESS_AMBIGUOUS"
    TABLE_EXTRACTION_FAILURE = "TABLE_EXTRACTION_FAILURE"
    UNSTRUCTURED_DOCUMENT = "UNSTRUCTURED_DOCUMENT"
    MULTIPLE_PLAUSIBLE_VALUES = "MULTIPLE_PLAUSIBLE_VALUES"
    NO_EVIDENCE = "NO_EVIDENCE"
    AI_REQUIRED = "AI_REQUIRED"


class OutputFormatType(StrEnum):
    NSF = "NSF"
    UB92 = "UB92"
    X12_837 = "X12_837"
    CANONICAL_JSON = "CANONICAL_JSON"


class ClaimFormType(StrEnum):
    CMS1500 = "CMS1500"
    UB04 = "UB04"
    UNSTRUCTURED = "UNSTRUCTURED"


class AuditEventType(StrEnum):
    DOCUMENT_RECEIVED = "DOCUMENT_RECEIVED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    PAGE_CLASSIFIED = "PAGE_CLASSIFIED"
    FIELD_EXTRACTED = "FIELD_EXTRACTED"
    FIELD_CORRECTED = "FIELD_CORRECTED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    MODEL_ESCALATED = "MODEL_ESCALATED"
    REVIEW_ASSIGNED = "REVIEW_ASSIGNED"
    REVIEW_DECIDED = "REVIEW_DECIDED"
    OUTPUT_GENERATED = "OUTPUT_GENERATED"
    OUTPUT_RECONCILED = "OUTPUT_RECONCILED"
    RECORD_DELETED = "RECORD_DELETED"
